---
- name: Install Terraform on Ubuntu
  hosts: all
  become: yes
  vars:
    terraform_version: "1.1.7"  # Set your desired Terraform version
    download_url: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"

  tasks:
    - name: Install unzip (needed for unzipping Terraform binary)
      apt:
        name: unzip
        state: present
        update_cache: yes

    - name: Download Terraform binary
      get_url:
        url: "{{ download_url }}"
        dest: "/tmp/terraform_{{ terraform_version }}.zip"
        mode: '0755'

    - name: Extract Terraform binary
      unarchive:
        src: "/tmp/terraform_{{ terraform_version }}.zip"
        dest: "/usr/local/bin/"
        remote_src: yes
        creates: "/usr/local/bin/terraform"

    - name: Remove downloaded zip file
      file:
        path: "/tmp/terraform_{{ terraform_version }}.zip"
        state: absent

    - name: Verify Terraform installation
      command: terraform version
      register: result

    - name: Output Terraform version
      debug:
        msg: "{{ result.stdout }}"
